volumes:
  db-data:
  log-data:
  consul-config:
  consul-data:
  vault-config:
  vault-pki:
  vault-file:
  vault-logs:

  vault:
    image: "edgexfoundry/docker-edgex-vault:latest"
    container_name: edgex-vault
    hostname: edgex-vault
    networks:
      - edgex-network
    ports:
      - "8200:8200"
    cap_add:
      - "IPC_LOCK"
    command: "server"
    environment:
      - 'VAULT_ADDR=https://edgex-vault:8200'
      - 'VAULT_CONFIG_DIR=/vault/config'
      - 'VAULT_UI=true'
    volumes:
      - vault-config:/vault/config
      - vault-pki:/vault/pki
      - vault-file:/vault/file
      - vault-logs:/vault/logs
    depends_on:
      - volume
      - consul

  vault-worker:
    image: "edgexfoundry/docker-edgex-vault-worker:latest"
    container_name: edgex-vault-worker
    hostname: edgex-vault-worker
    networks:
      - edgex-network
    environment:
      - 'WATCHDOG_DELAY=3m'
    volumes:
      - vault-pki:/vault/pki
      - vault-file:/vault/file
    depends_on:
      - volume
      - consul
      - vault
