#  ----------------------------------------------------------------------------------
#  docker-compose.yml	version 1.0 created February 8, 2018
#
#  @author:  Alain Pulluelo, ForgeRock
#  @email:   alain.pulluelo@forgerock.com
#  @address: 201 Mission St, Suite 2900
#            San Francisco, CA 94105, USA
#  @phone:   +1(415)-559-1100
#
#  Copyright (c) 2018, ForgeRock
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#  ----------------------------------------------------------------------------------
version: '3'

networks:
  myvaultnetwork:
    driver: bridge

services:
# At startup, the agent (in server mode) will read config JSON files from /consul/config.
# Data will be persisted in the /consul/data volume.
#
# https://github.com/hashicorp/docker-consul/blob/05523b3987523faa3820ae373abbe10c930c7283/0.X/Dockerfile
#
# VOLUME /consul/data
#
# Ports: This is a nested object that allows setting the bind ports for the following keys:
# dns        The DNS server, -1 to disable. Default 8600.
# http       The HTTP API, -1 to disable. Default 8500.
# https      The HTTPS API, -1 to disable. Default -1 (disabled).
# serf_lan   The Serf LAN port. Default 8301.
# serf_wan   The Serf WAN port. Default 8302.
# server     Server RPC address. Default 8300.
#
  consul-s1:
    image: "consul:latest"       # From Alpine 3.7 with Consul 1.0.5
    container_name: "myconsul-s1"
    networks:
      myvaultnetwork:
        aliases:
          - consul-s1.edgex.net
    hostname: "consul-s1"
    domainname: "edgex.net"
    extra_hosts:
      - "docker-host.edgex.net:192.168.99.100"
    dns:
      - 8.8.8.8
      - 4.4.4.4
    dns_search: edgex.net
    ports:
      - "8301:8301"  # Cluster: Serf LAN gossip between agents (consensus)
      - "8300:8300"  # RPC between Consul clients & servers for internal request forwarding
      - "8500:8500"  # HTTP UI/API
      - "8600:8600"  # DNS
    restart: always
    command: agent -server -client=0.0.0.0 -bind='{{ GetInterfaceIP "eth0" }}' -bootstrap-expect=3 -ui -log-level=debug
    environment:
      - 'CONSUL_LOCAL_CONFIG={
        "datacenter": "myDC", 
        "node_name": "consul-server-1", 
        "acl_datacenter":"myDC", 
        "acl_default_policy":"allow", "acl_down_policy":"allow", "acl_master_token":"a316c2ae-0dd3-11e8-b342-80e650282930"
        }'

  consul-s2:
    image: "consul:latest"
    container_name: "myconsul-s2"
    networks:
      myvaultnetwork:
        aliases:
          - consul-s2.edgex.net
    hostname: "consul-s2"
    domainname: "edgex.net"
    extra_hosts:
      - "docker-host.edgex.net:192.168.99.100"
    dns:
      - 8.8.8.8
      - 4.4.4.4
    dns_search: edgex.net
    restart: always
    command: agent -server -join consul-s1 -client=0.0.0.0 -bind='{{ GetInterfaceIP "eth0" }}' -log-level=debug
    environment:
      - 'CONSUL_LOCAL_CONFIG={
        "datacenter": "myDC", 
        "node_name": "consul-server-2", 
        "acl_datacenter":"myDC", 
        "acl_default_policy":"allow", "acl_down_policy":"allow", "acl_master_token":"a316c2ae-0dd3-11e8-b342-80e650282930"
        }'
    depends_on:
      - consul-s1

  consul-s3:
    image: "consul:latest"
    container_name: "myconsul-s3"
    networks:
      myvaultnetwork:
        aliases:
          - consul-s3.edgex.net
    hostname: "consul-s3"
    domainname: "edgex.net"
    extra_hosts:
      - "docker-host.edgex.net:192.168.99.100"
    dns:
      - 8.8.8.8
      - 4.4.4.4
    dns_search: edgex.net
    restart: always
    command: agent -server -join consul-s1 -client=0.0.0.0 -bind='{{ GetInterfaceIP "eth0" }}' -log-level=debug
    environment:
      - 'CONSUL_LOCAL_CONFIG={
        "datacenter": "myDC", 
        "node_name": "consul-server-3", 
        "acl_datacenter":"myDC", 
        "acl_default_policy":"allow", "acl_down_policy":"allow", "acl_master_token":"a316c2ae-0dd3-11e8-b342-80e650282930"
        }'
    depends_on:
      - consul-s1
      - consul-s2

  consul-c1:
    image: "consul:latest"
    container_name: "myconsul-c1"
    networks:
      myvaultnetwork:
        aliases:
          - consul-c1.edgex.net
    hostname: "consul-c1"
    domainname: "edgex.net"
    extra_hosts:
      - "docker-host.edgex.net:192.168.99.100"
    dns:
      - 8.8.8.8
      - 4.4.4.4
    dns_search: edgex.net
    restart: always
    command: agent -client=0.0.0.0 -bind='{{ GetInterfaceIP "eth0" }}'
    environment:
      - 'CONSUL_LOCAL_CONFIG={
        "datacenter": "myDC",
        "data_dir": "/consul/data",
        "acl_datacenter":"myDC",
        "acl_default_policy":"allow",
        "acl_down_policy":"allow",
        "acl_master_token":"a316c2ae-0dd3-11e8-b342-80e650282930",
        "enable_debug": true,
        "log_level": "DEBUG",
        "node_name": "consul-client-1",
        "server": false,
        "rejoin_after_leave": true,
        "retry_join": [
              "consul-s1.edgex.net",
              "consul-s2.edgex.net",
              "consul-s3.edgex.net"
             ]
        }'
    depends_on:
      - consul-s1
      - consul-s2
      - consul-s3

  consul-c2:
    image: "consul:latest"
    container_name: "myconsul-c2"
    networks:
      myvaultnetwork:
        aliases:
          - consul-c2.edgex.net
    hostname: "consul-c2"
    domainname: "edgex.net"
    extra_hosts:
      - "docker-host.edgex.net:192.168.99.100"
    dns:
      - 8.8.8.8
      - 4.4.4.4
    dns_search: edgex.net
    restart: always
    command: agent -client=0.0.0.0 -bind='{{ GetInterfaceIP "eth0" }}'
    environment:
      - 'CONSUL_LOCAL_CONFIG={
        "datacenter": "myDC",
        "data_dir": "/consul/data",
        "acl_datacenter":"myDC",
        "acl_default_policy":"allow",
        "acl_down_policy":"allow",
        "acl_master_token":"a316c2ae-0dd3-11e8-b342-80e650282930",
        "enable_debug": true,
        "log_level": "DEBUG",
        "node_name": "consul-client-2",
        "server": false,
        "rejoin_after_leave": true,
        "retry_join": [
              "consul-s1.edgex.net",
              "consul-s2.edgex.net",
              "consul-s3.edgex.net"
          ]
        }'
    depends_on:
      - consul-s1
      - consul-s2
      - consul-s3

  vault-s1:
    image: vault:latest
    container_name: "myvault-s1"
    networks:
      myvaultnetwork:
        aliases:
          - vault-s1.edgex.net
    hostname: "vault-s1"
    domainname: "edgex.net"
    extra_hosts:
      - "docker-host.edgex.net:192.168.99.100"
    dns:
      - 8.8.8.8
      - 4.4.4.4
    dns_search: edgex.net
#    build:
#      context: .
#      dockerfile: Dockerfile.consulClient
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    volumes:
        - ./pki/EdgeXTrustCA:/vault/pki:ro
    command: "server"
    environment:
      - 'VAULT_LOCAL_CONFIG={
        "listener": {
          "tcp":{ "address": "vault-s1.edgex.net:8200", "tls_disable": "0", 
                  "cluster_address": "vault-s1.edgex.net:8201",
                  "tls_min_version": "tls12",
                  "tls_client_ca_file": "/vault/pki/EdgeXTrustCA.pem",
                  "tls_cert_file": "/vault/pki/vault-s1.edgex.net.pem",
                  "tls_key_file": "/vault/pki/vault-s1.edgex.net.priv.key"}},
        "backend": {
          "consul":{ "path": "vault/", 
                     "address": "consul-c1.edgex.net:8500", "scheme": "http",
                     "redirect_addr": "https://vault-s1.edgex.net:8200",
                     "cluster_addr": "https://vault-s1.edgex.net:8201"}},
        "default_lease_ttl": "168h",
        "max_lease_ttl": "720h"
        }'
      - 'VAULT_ADDR=https://vault-s1.edgex.net:8200'
    depends_on:
      - consul-c1

  vault-s2:
    image: vault:latest
    container_name: "myvault-s2"
    networks:
      myvaultnetwork:
        aliases:
          - vault-s2.edgex.net
    hostname: "vault-s2"
    domainname: "edgex.net"
    extra_hosts:
      - "docker-host.edgex.net:192.168.99.100"
    dns:
      - 8.8.8.8
      - 4.4.4.4
    dns_search: edgex.net
    cap_add:
      - IPC_LOCK
    ports:
      - "8201:8200"
    volumes:
        - ./pki/EdgeXTrustCA:/vault/pki:ro
    command: "server"
    environment:
      - 'VAULT_LOCAL_CONFIG={
        "listener": {
          "tcp":{ "address": "vault-s2.edgex.net:8200", "tls_disable": "0", 
                  "cluster_address": "vault-s1.edgex.net:8201",
                  "tls_min_version": "tls12",
                  "tls_client_ca_file": "/vault/pki/EdgeXTrustCA.pem",
                  "tls_cert_file": "/vault/pki/vault-s2.edgex.net.pem",
                  "tls_key_file": "/vault/pki/vault-s2.edgex.net.priv.key"}},
        "backend": {
          "consul":{ "path": "vault/", 
                     "address": "consul-c2.edgex.net:8500", "scheme": "http",
                     "redirect_addr": "https://vault-s2.edgex.net:8200",
                     "cluster_addr": "https://vault-s2.edgex.net:8201"}},
        "default_lease_ttl": "168h",
        "max_lease_ttl": "720h"
        }'
      - 'VAULT_ADDR=https://vault-s2.edgex.net:8200'
    depends_on:
      - consul-c2
      - vault-s1
